/// Flutter icons FlatIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlatIcons
///      fonts:
///       - asset: fonts/FlatIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FlatIcons {
  FlatIcons._();

  static const _kFontFam = 'FlatIcons';
  static const String _kFontPkg = null;

  static const IconData airline_seat_individual_suite = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knife_fork = IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bath_1 = IconData(0xf2cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler_combined = IconData(0xf546, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
